import Head from "next/head";
import { Card, Space, Typography } from "antd";
import { Inter } from "next/font/google";
import styles from "src/styles/Home.module.css";
import Link from "next/link";
import useLocalStorage from "@/hooks/useLocalStorage";
import { SELECTED_LANGUAGE_KEY } from "@/utils/const";
import { blue } from '@ant-design/colors';
import useTrans from "@/hooks/useTrans";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [locale] = useLocalStorage<string>(SELECTED_LANGUAGE_KEY, "");
  const trans = useTrans();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header />
        <Typography.Title style={{textAlign: 'center'}}>{trans['app.title']}</Typography.Title>
        <Link href="/replacement-app" locale={locale}>
          <Card title={trans['replacement_app']} style={{width: '30vw'}}>
            <Typography style={{color: blue.primary}}>
              {trans['replacement_app_description']}
            </Typography>
          </Card>
        </Link>
      </main>
    </>
  );
}
